CI: Aggregate coverage from multiple jobs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,26 +18,67 @@ env:
   - DB=mysqli
 
 before_install:
-  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
+  - |
+    if [ "x$COVERAGE" != "xyes" ]; then
+      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
+    fi
 
 before_script:
   - if [[ "$DB" == "mysql" || "$DB" == "mysqli" || "$DB" == *"mariadb"* ]]; then mysql < tests/travis/create-mysql-schema.sql; fi;
+  - |
+    if [ "x$COVERAGE" == "xyes" ] && [[ ! $(php -m | grep -si xdebug) ]]; then
+      echo "xdebug is required for coverage"
+      exit 1
+    fi
 
 install:
   - rm composer.lock
   - travis_retry composer -n update --prefer-dist
 
-script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
+script:
+  - |
+    if [ "x$COVERAGE" == "xyes" ]; then
+       ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml --coverage-clover clover.xml
+    else
+       ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
+    fi
+
+after_script:
+  - |
+    if [ "x$COVERAGE" == "xyes" ]; then
+      wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
+      php ocular.phar code-coverage:upload --format=php-clover clover.xml
+    fi
 
 jobs:
   allow_failures:
     - php: nightly
     - stage: Coding standard
 
+  exclude:
+    - php: 7.1
+      env: DB=sqlite
+    - php: 7.1
+      env: DB=mysql
+    - php: 7.1
+      env: DB=mysqli
+
   include:
     - stage: Test
       php: 7.1
-      env: DB=mysql MYSQL_VERSION=5.7
+      env: DB=sqlite COVERAGE=yes
+
+    - stage: Test
+      php: 7.1
+      env: DB=mysql COVERAGE=yes
+
+    - stage: Test
+      php: 7.1
+      env: DB=mysqli COVERAGE=yes
+
+    - stage: Test
+      php: 7.1
+      env: DB=mysql MYSQL_VERSION=5.7 COVERAGE=yes
       sudo: required
       before_script:
         - bash ./tests/travis/install-mysql-5.7.sh
@@ -56,7 +97,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mysqli MYSQL_VERSION=5.7
+      env: DB=mysqli MYSQL_VERSION=5.7 COVERAGE=yes
       sudo: required
       before_script:
         - bash ./tests/travis/install-mysql-5.7.sh
@@ -75,7 +116,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb MARIADB_VERSION=10.0
+      env: DB=mariadb MARIADB_VERSION=10.0 COVERAGE=yes
       addons:
         mariadb: 10.0
     - stage: Test
@@ -91,7 +132,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb MARIADB_VERSION=10.1
+      env: DB=mariadb MARIADB_VERSION=10.1 COVERAGE=yes
       addons:
         mariadb: 10.1
     - stage: Test
@@ -107,7 +148,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb MARIADB_VERSION=10.2
+      env: DB=mariadb MARIADB_VERSION=10.2 COVERAGE=yes
       addons:
         mariadb: 10.2
     - stage: Test
@@ -123,7 +164,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=mariadb.mysqli MARIADB_VERSION=10.2
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.2 COVERAGE=yes
       addons:
         mariadb: 10.2
     - stage: Test
@@ -139,7 +180,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.2
+      env: DB=pgsql POSTGRESQL_VERSION=9.2 COVERAGE=yes
       services:
         - postgresql
       addons:
@@ -161,7 +202,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.3
+      env: DB=pgsql POSTGRESQL_VERSION=9.3 COVERAGE=yes
       services:
         - postgresql
       addons:
@@ -183,7 +224,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.4
+      env: DB=pgsql POSTGRESQL_VERSION=9.4 COVERAGE=yes
       services:
         - postgresql
       addons:
@@ -205,7 +246,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.5
+      env: DB=pgsql POSTGRESQL_VERSION=9.5 COVERAGE=yes
       services:
         - postgresql
       addons:
@@ -227,7 +268,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=9.6
+      env: DB=pgsql POSTGRESQL_VERSION=9.6 COVERAGE=yes
       services:
         - postgresql
       addons:
@@ -249,7 +290,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pgsql POSTGRESQL_VERSION=10.0
+      env: DB=pgsql POSTGRESQL_VERSION=10.0 COVERAGE=yes
       sudo: required
       services:
         - postgresql
@@ -279,7 +320,7 @@ jobs:
         - bash ./tests/travis/install-postgres-10.sh
 
     - stage: Test
-      env: DB=sqlsrv
+      env: DB=sqlsrv COVERAGE=yes
       sudo: required
       services:
         - docker
@@ -298,7 +339,7 @@ jobs:
 
     - stage: Test
       php: 7.1
-      env: DB=pdo_sqlsrv
+      env: DB=pdo_sqlsrv COVERAGE=yes
       sudo: required
       services:
         - docker
@@ -328,18 +369,6 @@ jobs:
       install:
         - composer config minimum-stability dev
         - travis_retry composer update --prefer-dist
-
-    - stage: Coverage
-      php: 7.1
-      env: DB=sqlite
-      before_script:
-        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
-        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
-      script:
-        - ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml --coverage-clover clover.xml
-      after_script:
-        - wget https://scrutinizer-ci.com/ocular.phar
-        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
 
     - stage: Pull request coding standard
       if: type = pull_request
